options:
  prefix: "&e[&6&lUHC&e]"
  ip: "play.premium-uhc.com"
  scoreboard-name: "&6&lPREMIUM UHC"
  bungeecord:
    server-lobby: "lobby"
    server-host: "host-1"
  spawn:
    coords: "0, 100, 0, 0f, 0f"
  game:
    max-player: 8
    time-mining:
      second: 0
      minute: 1
    world-border:
      center:
        x: 0
        y: 0
      size: 500
      last-size: 25
      speed-in-block: 1.0
  config-host:
    teams:
      team-limit: 8
      player-limit-per-team: 4

messages:
  console:
    enable-message: "%prefix% &rLe plugin vient de se démarrer."
    disable-message: "%prefix% &rLe plugin s'est éteint."
  host:
    be-host-message: "%prefix% &fFélicitation ! Vous êtes devenu le hôte de cette partie, faites &c/uhc start &fpour démarrer le compte à rebours."
    info-host-start-message: "%prefix% &aVous avez démarré le compte à rebours !"
    not-enough-players-message: "%prefix% &cIl n'y a pas assez de joueur pour démarrer la partie (Minimum 2 joueurs sont nécessaire)."
    no-host-permission-message: "%prefix% &cVous n'avez pas la permission de faire cela, vous n'êtes pas l'hôte de cette partie."
    kick:
      no-pseudo-message: "%prefix% &cVous devez entrer le pseudo d'un joueur pour l'expulser."
      player-not-online: "%prefix% &cLe joueur n'est pas connecté ou n'existe pas."
      be-kick-message: "%prefix% &cVous avez été expulsé du serveur par l'hôte de la partie."
      successfully-kick-message: "%prefix% &fLe joueur &c%player% &fà bien été expulsé du serveur."
  timer:
    one-second: "seconde"
    several-seconds: "secondes"
    timer-message: "%prefix% &eLa partie commence dans &c%time% &e%second%."
    end-timer-message: "%prefix% &eLa partie commence, téléportation en cours..."
  end:
    end-game-message: "%prefix% &fLa partie est terminée, l'heureux &evainqueur &fest &6%winner%&f, Faites un tonnerre de &c&lGG &fà lui ! %nl%&eTéléportation au lobby dans quelques instants..."
  kill:
    death-message-toplayer: "%prefix% &cVous êtes mort &fpar &c%killer%&f, vous êtes passé en &cmode spectateur&f."
    death-message-byplayer: "%prefix% &c%player% &fest mort par %killer%"
    death-message-alone: "%prefix% &c%player% &fest mort"
  config-host:
    teams:
      team-limit-message: "%prefix% &cErreur: La limite du nombre d'équipe à été atteinte (8 Équipes maximum)."
      player-limit-per-team-message: "%prefix% &cErreur: La limite de joueur par équipe à été atteinte (4 Joueurs par équipe maximum)."
      min-team-message: "%prefix% &cErreur: Minimum de 2 équipes dans la partie."
      min-player-per-team-message: "%prefix% &cErreur: Minimum de 1 joueur par équipe."
  be-spectator-message: "%prefix% &fLa partie a déjà commencé, vous êtes passez en mode spectateur."
  join-message: "%prefix% &7[&a+&7] &7%player%"
  quit-message: "%prefix% &7[&c-&7] &7%player%"
  help: "%nl%&f---------- &c&lHELP &f----------%nl%&c/uhc start &6&l✯ &fDémarrer la partie de UHC.%nl%&c/uhc options &6&l✯ &fConfigurer la partie.%nl%&c/uhc kick <joueur> &6&l✯ &fExpulser un joueur de la partie.%nl%&c/uhc stats &fAccéder à ses statistiques.%nl%&c/uhc info &fInformations sur la partie.%nl%&c/uhc scenarios &fVoir la liste des scénarios.%nl%&c/uhc inventaire &fVoir l'inventaire de départ.%nl%&c/uhc leave &fpour quitter la partie de UHC et retourner au Lobby.%nl%--------------------------%nl% "
  stats: "%nl%&f---------- &c&lSTATS &f----------%nl% &fNombre de parties jouées: &b%total-party% %nl% &fNombre de parties gagnées: &6%total-victory% %nl% &fNombre de kills: &c%total-kills% %nl%&f----------------------------"

title:
  timer:
    five-second-title: "&2&l5"
    four-second-title: "&a&l4"
    three-second-title: "&c&l3"
    two-second-title: "&c&l2"
    one-second-title: "&c&l1"
    final-second-title: "&a&lGo !"
  victory:
    victory-title: "&eVictoire !"

spawns-coords:
  - "-100, 100, 100, 0f, 0f"
  - "100, 100, -100, 0f, 0f"
  - "0, 100, 100, 0f, 0f"
  - "0, 100, -100, 0f, 0f"
  - "100, 100, 0, 0f, 0f"
  - "-100, 100, 0, 0f, 0f"
  - "100, 100, 100, 0f, 0f"
  - "-100, 100, -100, 0f, 0f"

scoreboard-waiting:
  - "&7%date%"
  - "&7"
  - "&6&l%player%"
  - "&7▪ &fParties jouées: &b%total-party%"
  - "&7▪ &fKills: &c%total-kills%"
  - "&7▪ &fVictoires: &6%total-victory%"
  - "&1"
  - "&e&lServeur"
  - "&7▪ &fJoueurs: &3%player-ingame%&7/&3%player-max%"
  - "&7▪ &fHôte: &c%host-owner%"
  - "&d"
  - "&e%server-ip%"

scoreboard-starting:
  - "&7%date%"
  - "&7"
  - "&6&lDémarrage"
  - "&7▪ &fDébut dans &e%time%&fs"
  - "&7▪ &fMode: &bSolo"
  - "&d"
  - "&e&lServeur"
  - "&7▪ &fJoueurs: &3%player-ingame%&7/&3%player-max%"
  - "&7▪ &fHôte: &c%host-owner%"
  - "&1"
  - "&e%server-ip%"

scoreboard-mining:
  - "&7%date%"
  - "&7"
  - "&6&lMinage"
  - "&7▪ &fBordure: &6%border-time%"
  - "&7▪ &fPvP: &b%pvp-time%"
  - "&1"
  - "&e&lStats"
  - "&7▪ &fKills: &e%total-kill%"
  - "&7▪ &fJoueurs: &6%players-left%"
  - "&d"
  - "&e%server-ip%"

scoreboard-playing:
  - "&7%date%"
  - "&7"
  - "&6&lEn jeu"
  - "&7▪ &fTemps: &c%minute-ingame%:%second-ingame%"
  - "&7▪ &fBordure: &6%border%"
  - "&7▪ &fPvP: &b%pvp-time%"
  - "&1"
  - "&e&lStats"
  - "&7▪ &fKills: &e%total-kill%"
  - "&7▪ &fJoueurs: &6%players-left%"
  - "&d"
  - "&e%server-ip%"

scoreboard-end:
  - "&7%date%"
  - "&7"
  - "&c&lFin"
  - "&7▪ &fGagnant: &6%winner%"
  - "&7▪ &fTemps joué: &c%minute-ingame%:%second-ingame%"
  - "&1"
  - "&e%server-ip%"